### ISSUE TITLE
Fix responsiveness

### ISSUE THREAD

**Issue by AbhineshJha** [Kritika30032002/Blog_Website#114] opened 2024-01-22 10:53 UTC
After clicking the toggle button of responsive it gets merged with navbar 

![image](https://github.com/Kritika30032002/Blog_Website/assets/142514166/1e9f1042-3d47-4970-a44d-16bdf1dd4513)

/assign under iwoc

**Comment by Prince-kushwaha-2004** [comment] 2024-01-30 11:48
@Kritika30032002 
If the issue is not resolve yet You can assign it to me  under IWOC2024.
I would like to contribute.

**Closed** 2024-01-30 13:36 UTC
Labels: easy, iwoc2024
