### ISSUE TITLE
[Bug]: Signup/SignIn Not working properly

### ISSUE THREAD

**Issue by jiveshkalra** [Kritika30032002/Blog_Website#140] opened 2024-03-12 12:01 UTC
### What happened?

When I tried to signup , this mongo db error poped up
![image](https://github.com/Kritika30032002/Blog_Website/assets/127482713/56b7d203-5a3c-4210-b3fd-9e3f903ba3d7)
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kritika30032002** [comment] 2024-03-12 17:00
Max 2 issues can be assigned at a time. After completing them you can get these assigned if they are open.

**Comment by timmySpark** [comment] 2024-03-16 19:15
@Kritika30032002 , can this issue be assigned to me ?

**Comment by jiveshkalra** [comment] 2024-03-17 03:37
@timmySpark buddy im already onto it ,

**Comment by timmySpark** [comment] 2024-03-17 04:41
okay @jiveshkalra

**Comment by Sagar-03** [comment] 2024-03-24 19:06
Hii @Kritika30032002 
It has come to my attention that our signup page is currently experiencing difficulties, resulting in a significant decrease in website reach and hindering users from signing up successfully. Upon investigating the root cause, it has been identified that the issue stems from a MongoDB failure in the backend of our website.

Understanding the critical nature of this problem and having the necessary expertise to address it, I kindly request to be assigned to resolve this issue promptly. I am confident in my ability to diagnose and implement the required fix to restore the signup functionality and mitigate any further impact on our website's performance.

By resolving this issue swiftly, we can ensure uninterrupted service for our users and prevent any potential loss of engagement or revenue. I am fully committed to dedicating my efforts to resolving this matter efficiently and effectively.

`Please consider this as a formal request for assignment to address the signup page issue caused by MongoDB failure`

Looking forward to contribute to the project

**Comment by Kritika30032002** [comment] 2024-03-24 20:26
@jiveshkalra What's the update?

**Comment by jiveshkalra** [comment] 2024-03-25 10:22
onto it , sorry i was a bit busy with the fullstack part of the hackathon and some other comps 
finally got free from all that

**Comment by Kritika30032002** [comment] 2024-03-26 17:34
will you complete this ?

**Comment by Sagar-03** [comment] 2024-03-26 18:58
@Kritika30032002  can you please assign it to me as well also

**Comment by Kritika30032002** [comment] 2024-03-26 20:47
@timmySpark do you want to do it?

**Comment by jiveshkalra** [comment] 2024-03-27 09:33
uhmm.. I fixed it ...
I did mention I was a bit busy with all the India AI Youth Awards, so sorry for the delay 
but its not much big of a problem
just .env file is missing 
create that n its fixed

**Closed** 2024-10-10 11:03 UTC
Labels: bug
